version: 2.1

orbs:
  node: circleci/node@5.1.0
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - store_test_results:
          path: test-results
  # deploy:
  #   executor: heroku/default
  #   steps:
  #     - attach_workspace:
  #         at: ~/project
  #     - heroku/deploy-via-git:
  #         force: true #

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test
      #     filters:
      #       branches:
      #         only: main
